name: openscan
description: An open source app that enables users to scan hardcopies of
  documents or notes and covert it to a PDF file. No ads, privacy is of the
  utmost importance.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_scanner_cropper:
    git:
      url: https://github.com/Ethereal-Developers-Inc/flutter-scanner-plugin.git
      path: flutter_scanner_cropper/
  cupertino_icons: ^0.1.3
  flutter_absolute_path: ^1.0.6
  flutter_full_pdf_viewer: ^1.0.6
  flutter_speed_dial: ^1.2.5
  focused_menu: ^1.0.1
  image_picker: ^0.6.4
  multi_image_picker: ^4.8.0
  open_file: ^3.0.3
  path_provider: ^2.0.2
  pdf: ^1.9.0
  permission_handler: ^8.0.1
  quick_actions: ^0.6.0+2
  reorderables: ^0.3.2
  share_extend: ^1.1.9
  shared_preferences: ^0.5.7+3
  simple_animated_icon: ^1.0.0
  sqflite: ^1.3.1+2
  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
