name: openscan
description: An open source app that enables users to scan hardcopies of
  documents or notes and covert it to a PDF file. No ads, privacy is of the
  utmost importance.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.0+5

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  camera: ^0.10.0+1
  cupertino_icons: ^1.0.3
  exif: ^3.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  # flutter_neumorphic: ^3.1.0
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_speed_dial: ^5.0.0+1
  # fluttertoast: ^8.0.8
  focused_menu: ^1.0.5
  image: ^3.2.0
  image_picker: ^0.8.4+2
  intl: ^0.17.0
  multi_image_picker: ^4.8.01
  open_file: ^3.2.1
  path: ^1.8.2
  path_provider: ^2.0.5
  pdf: ^3.6.0
  permission_handler: ^8.1.6
  quick_actions: ^0.6.0+7
  reorderables: ^0.4.1
  sensors_plus: ^1.2.1
  share_extend: ^2.0.0
  shared_preferences: ^2.0.8
  simple_animated_icon: ^1.1.0
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.12
  vector_math: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
