name: openscan
description: An open source app that enables users to scan hardcopies of
  documents or notes and covert it to a PDF file. No ads, privacy is of the
  utmost importance.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.0+4

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_scanner_cropper:
    git:
      url: https://github.com/Ethereal-Developers-Inc/flutter-scanner-plugin.git
      ref: null_safety_migration_branch
      path: flutter_scanner_cropper/
  cupertino_icons:
  flutter_speed_dial:
  focused_menu:
  image_picker:
  open_filex:
  path_provider:
  pdf:
  permission_handler:
  quick_actions:
  reorderables:
  share_extend:
  shared_preferences:
  simple_animated_icon:
  sqflite:
  url_launcher:

  path: any
  flutter_gen: any
  vector_math: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
